config/routes.rb
Tweetability::Application.routes.draw do

  root "sessions#new"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  resources :sessions

  resources :users do
    resource :tweets do
      collection do
        get 'list'
      end
      get 'fetch'
    end
  end

  get 'users/:id/tweets/fetch' => 'tweets#fetch'
end

app/models/pattern.rb
class Pattern < ActiveRecord::Base
  has_many :tweets
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :pattern

  def self.save_all tweets
    tweets.each do |t|
      tweet = Tweet.new(t)
      tweet.save
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :name
  validates_uniqueness_of :name
  validates_presence_of :handle

  def self.authenticate (username, password)
    user = find_by name: username
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :require_login
  helper_method :current_user

  private
  def require_login
    redirect_to log_in_path unless session[:user_id]
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/patterns_controller.rb
class PatternsController < ApplicationController
  def new

  end

  def create
    @pattern = Pattern.new(post_params)
    @pattern.save

    redirect_to @pattern
  end

  def show
    @pattern = Pattern.find(params[:id])
  end

  private
  def post_params
    params.require(:pattern).permit(:title, :pattern)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    user = User.authenticate(params[:name], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash[:alert] = "Invalid username or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def fetch
    user_id = params[:user_id].to_i
    @tweets_fetcher ||= TweetsFetcher.new
    @tweets_fetcher.fetch_new_tweets user_id
    redirect_to list_user_tweets_path user_id
  end

  def list
    @tweets = Tweet.where :user_id => params[:user_id]
  end

  def load_tweets_fetcher(fetcher)
    @tweets_fetcher = fetcher
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  # creates a user
  def create
    @user = User.new(post_params)

    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def post_params
    params.require(:user).permit(:name, :password, :password_confirmation, :handle)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patterns_helper.rb
module PatternsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tweetability</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="user_nav">
  <% if current_user %>
    Logged in as <%= current_user.name %>.
    <%= link_to "Log out", log_out_path %>
  <% else %>
    <%= link_to "Sign up", sign_up_path %> or
    <%= link_to "log in", log_in_path %>
  <% end %>
</div>

<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
<% end -%>

<%= yield %>

</body>
</html>

app/views/patterns/index.html.erb
<h1>Patterns#index</h1>
<p>Find me in app/views/patterns/index.html.erb</p>

app/views/patterns/new.html.erb
<h1>New Pattern</h1>
<%= form_for :pattern, url: patterns_path do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :pattern %>
    <%= f.text_field :pattern %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/patterns/show.html.erb
<h1>Pattern</h1>
<p>
  <strong>Title: </strong>
  <%= @pattern.title %>
</p>
<p>
  <strong>Pattern: </strong>
  <%= @pattern.pattern %>
</p>

<p>
  <%= link_to "Fetch Tweets", :controller => "tweets", :action => "list", :pattern_id => @pattern.id %>
</p>

app/views/tweets/list.html.erb
<h1>Tweets</h1>

<%= @tweets.each do |tweet| %>
<p>
  <strong>Text: </strong>
  <span>
    <%= tweet.text %>
  </span>
</p>
<% end %>

app/views/tweets/show.html.erb
<h1>Tweets</h1>

<%= @tweets.each do |tweet| %>
<p>
  <strong>Text: </strong>
  <%= tweet.text %>
</p>
<% end %>

app/views/users/new.html.erb
<h1>Signup with tweetability</h1>
<%= form_for @user do |form| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= form.label :name, 'Username' %><br />
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :password %><br />
    <%= form.password_field :password %>
  </p>
  <p>
    <%= form.label :password_confirmation %><br />
    <%= form.password_field :password_confirmation %>
  </p>
  <p>
    <%= form.label :handle %><br />
    <%= form.text_field :handle %>
  </p>
  <p>
    <%= form.submit 'Do signup' %>
  </p>
<% end %>

app/views/users/show.html.erb
<h1>User details for <%= @user.name %></h1>
<p>
  <strong>Handle: </strong>
  <%= @user.handle %>

<p>
  <%= link_to "All fetched tweets", list_user_tweets_path(@user.id) %>
</p>

<p>
  <%= link_to "Fetch tweets", fetch_user_tweets_path(@user.id) %>
</p>